### PR TITLE
Movies index page

### PR DESCRIPTION
**Pull request by dewaldreynecke**
Creates a movies index page with a card for each movie and a link to the show page.
3-column CSS grid that will resize to 2-columns and later 1-column on smaller screens via media queries.

### CODE REVIEW

**Comment by dewaldreynecke** [comment]
Resolved the merge conflicts.

**Comment by dewaldreynecke** [comment]
The design of the cards is not the prettiest but we can always come back to restyle once we have all the parts of our app present and working. I have added a task in the Trello for it.

**Comment by dewaldreynecke** [comment]
Here is a preview:
Screenshot 2023-05-30 at 12 44 08

**Comment by Mosiami87** [comment]
The index page looks good for now

**Pull request merged**
